#       ----------- + AdminBans by Ziga Zajc + -----------   #
#                                                            #
#                            Config                          #
#                                                            #
#       --------- + ------------------------- + ----------   #
#
#       You can use chat colors:
#                ________________________
#               |   code: | color:       |
#               |________________________|
#               |     &0  |	Black	     |
#               |     &1  |	Dark Blue	 |
#               |     &2  |	Dark Green	 |
#               |     &3  |	Dark Aqua	 |
#               |     &4  |	Dark Red	 |
#               |     &5  |	Dark Purple	 |
#               |     &6  |	Gold	     |
#               |     &7  |	Gray	     |
#               |     &8  |	Dark Gray	 |
#               |     &9  |	Blue	     |
#               |     &a  |	Green	     |
#               |     &b  |	Aqua	     |
#               |     &c  |	Red	         |
#               |     &d  |	Light Purple |
#               |     &e  |	Yellow	     |
#               |     &f  |	White	     |
#               |     &k  |	Obfuscated	 |
#               |     &l  |	Bold	     |
#               |     &m  |	Strikethrough|
#               |     &n  |	Underline	 |
#               |     &o  |	Italic	     |
#               |     &r  |	Reset	     |
#               |________________________|
#
#----------------------------------------------------------
#                      Server Name
#----------------------------------------------------------
server_name: "Global"
#----------------------------------------------------------
#                        Reasons
#----------------------------------------------------------
reasons:
  - "Advertising"
  - "Hacking"
  - "Swearing"
  - "Griefing"
  - "Spamming"
#----------------------------------------------------------
#                        Times
#  (min = minute, h = hour, d = day, m = month, y = year)
#----------------------------------------------------------
times:
  - "15min"
  - "30min"
  - "1h"
  - "3h"
  - "5h"
  - "1d"
  - "5d"
  - "10d"
  - "1m"
  - "3m"
  - "10m"
  - "1y"
  - "3y"
  - "10y"
#----------------------------------------------------------
#             Commands restriction when muted
#----------------------------------------------------------
mute_commands_restriction:
  - "/msg"
#----------------------------------------------------------
#   MySQL Database - Must be used for Website Interface
#----------------------------------------------------------
# Do you want to use mysql database?
mysql: false
# Here are all data for connection to Mysql database. Please create database, user and password by yourself. Do not use root as user, because of security risk!
mysql_host: "localhost"
mysql_port: "3306"
mysql_database: "AdminBans"
mysql_user: "root"
mysql_password: ""
mysql_useSSL: false